### ISSUE TITLE
BendingGUI Error

### ISSUE THREAD

**Issue by Manaenk0v** [StrangeOne101/BendingGUI#11]
Spigot 1.18.2
ProjectKorra 1.9.3

[19:35:08] [Server thread/WARN]: [BendingGUI] Task #1048747 for BendingGUI v1.2.2 generated an exception
java.lang.NullPointerException: Cannot invoke "com.projectkorra.projectkorra.BendingPlayer.isToggled()" because the return value of "com.projectkorra.projectkorra.BendingPlayer.getBendingPlayer(String)" is null
	at com.strangeone101.bendinggui.menus.MenuBendingOptions.getBendingToggle(MenuBendingOptions.java:485) ~[BendingGUI.jar:?]
	at com.strangeone101.bendinggui.menus.MenuBendingOptions.update(MenuBendingOptions.java:859) ~[BendingGUI.jar:?]
	at com.strangeone101.bendinggui.menus.MenuBendingOptions$13.run(MenuBendingOptions.java:946) ~[BendingGUI.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-277]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.2.jar:git-Paper-277]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[paper-1.18.2.jar:git-Paper-277]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-277]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-277]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-277]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-277]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by StrangeOne101** [comment]
This plugin is not updated for ProjectKorra 1.9.3. It hasn't been updated for years lol

**Comment by Manaenk0v** [comment]
So what? I understand that, but it works fine apart from this error

> This plugin is not updated for ProjectKorra 1.9.3. It hasn't been updated for years lol

**Comment by StrangeOne101** [comment]
Not sure. The error itself stems from ProjectKorra, so it could be a version thing or just an issue on their end

**Comment by StrangeOne101** [comment]
Can you please test if this still occurs on the latest version? (1.3 - freshly released)

**Comment by StrangeOne101** [comment]
Bump @Manaenk0v. I'll give this a few days and then close it if I don't get anything further
