### ISSUE TITLE
NPE Opening GUI

### ISSUE THREAD

**Issue by StrangeOne101** [StrangeOne101/BendingGUI#2]
# Exception
```
21.02 14:51:14 [Server] WARN java.lang.NullPointerException
21.02 14:51:14 [Server] WARN at com.strangeone101.bendinggui.menus.MenuBendingOptions.<init>(MenuBendingOptions.java:63)
21.02 14:51:14 [Server] WARN at com.strangeone101.bendinggui.Listener.onItemRightClick(Listener.java:45)```

# Issue Environment 
Mostly unknown. I believe it was reported on MC 1.12 and PK 1.8.6 with the latest version of the plugin.

**Comment by StrangeOne101** [comment]
Fixed in #5, so closed.
